# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ZettlabPublish < Formula
  desc "Zettlab internal operator CLI for publishing flows."
  homepage "https://github.com/zettlab/zettlab-server"
  version "0.1.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zettlab/homebrew-tap/releases/download/v0.1.6/zettlab-publish_0.1.6_darwin_amd64.tar.gz"
      sha256 "f4a9055a0337117c0043dd195617c860e246ce59426b8a08ee77cdd26e55a5ba"

      define_method(:install) do
        bin.install "zettlab-publish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zettlab/homebrew-tap/releases/download/v0.1.6/zettlab-publish_0.1.6_darwin_arm64.tar.gz"
      sha256 "c1a39c1de6d38f844cebc0da8aa33c3f0e371e264819b1ea35294c11e2de0016"

      define_method(:install) do
        bin.install "zettlab-publish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zettlab/homebrew-tap/releases/download/v0.1.6/zettlab-publish_0.1.6_linux_amd64.tar.gz"
      sha256 "d49e0a33ce9a74bf6d7fa48313f670fe8372b864cb35281a5970298b895c6af8"
      define_method(:install) do
        bin.install "zettlab-publish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zettlab/homebrew-tap/releases/download/v0.1.6/zettlab-publish_0.1.6_linux_arm64.tar.gz"
      sha256 "6069316a7178f1c00184cb0560f01f2f7bfbd4399ef6948a80232eafcd008cde"
      define_method(:install) do
        bin.install "zettlab-publish"
      end
    end
  end

  test do
    system "#{bin}/zettlab-publish", "version"
  end
end
