# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../lib/zettlab_private_release_download_strategy"
class ZettlabPublish < Formula
  desc "Zettlab internal operator CLI for publishing flows."
  homepage "https://github.com/zettlab/zettlab-server"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zettlab/zettlab-server/releases/download/v0.1.0/zettlab-publish_0.1.0_darwin_amd64.tar.gz", using: ZettlabPrivateReleaseDownloadStrategy,
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "3d31832f35467e8e7df59050c4e77ba7738744d731485bd4bcb8d802401de248"

      define_method(:install) do
        bin.install "zettlab-publish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zettlab/zettlab-server/releases/download/v0.1.0/zettlab-publish_0.1.0_darwin_arm64.tar.gz", using: ZettlabPrivateReleaseDownloadStrategy,
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "e7f3b24523373f7cd7b39a73bbaeb2c117748afaad82242e85168c00c9a3f074"

      define_method(:install) do
        bin.install "zettlab-publish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zettlab/zettlab-server/releases/download/v0.1.0/zettlab-publish_0.1.0_linux_amd64.tar.gz", using: ZettlabPrivateReleaseDownloadStrategy,
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "20fbeb906770ee40648d084913583c59dd82c53f55c61ca8bb6e99ab8943162c"
      define_method(:install) do
        bin.install "zettlab-publish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zettlab/zettlab-server/releases/download/v0.1.0/zettlab-publish_0.1.0_linux_arm64.tar.gz", using: ZettlabPrivateReleaseDownloadStrategy,
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "035b5da7c529863acfa0129db8e3b5911f285135c3d8676b7e0d17fdec6c00f8"
      define_method(:install) do
        bin.install "zettlab-publish"
      end
    end
  end

  def caveats
    <<~EOS
      zettlab-publish release assets are private. Set HOMEBREW_GITHUB_API_TOKEN
      to a GitHub token that can read zettlab/zettlab-server before installing
      or upgrading this formula.
    EOS
  end

  test do
    system "#{bin}/zettlab-publish", "version"
  end
end
